[phases.setup]
nixPkgs = ['python310', 'gcc', 'libffi']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[start]
cmd = 'cd backend && gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
